### PR TITLE
Upload every build to GCS

### PR DESCRIPTION
**Pull request by beeender**
As versioned file.

### CODE REVIEW

**Comment by beeender** [comment]
See testing pipeline here
https://extensions.ci.gpdb.pivotal.io/teams/main/pipelines/DEV:mulong_diskquota

**Comment by xuebinsu** [comment]
Since we cannot use VERSION here, can we add a file that contains the latest commit hash when doing `tar`  to identify our dev build?

**Comment by beeender** [comment]
No need, easy to know the info from the concourse for every build 
image

**Review by Sasasu — APPROVED** [review]

**Comment by Sasasu** [comment]
I prefer to embed the build info in the binary if the build info is relay needed.
image

**Comment by beeender** [comment]
> I prefer to embed the build info in the binary if the build info is relay needed.

It is doable. Any benefit by embedding into a binary file?
The current text file is mostly for our internal usage. e.g.: PM downloaded a binary from pipeline and found a problem. Then we can based on the text file in the tarball to identify where the binary was built from.

**Review by Sasasu — APPROVED** [review]
LGTM, the build info will not be copied to GPDB

**Review by xuebinsu — APPROVED** [review]

**Pull request merged**
