### PR TITLE
Fix memory leak

### PR DESCRIPTION
**Pull request by zhrt123**
StringInfoData should be free in init/vacuum hashtable function.

### CODE REVIEW

**Comment by zhrt123** [comment]
> So much changes?

I've rebased the branch with `move-reject-map`. The changes will look less.

**Review by fanfuxiaoran — APPROVED** [review]

**Comment by fanfuxiaoran** [comment]
LGTM! Maybe use the memory context to manage the memory is better in the future.

**Comment by beeender** [comment]
Does the leak happen to 2.x as well?

**Comment by zhrt123** [comment]
> Member
> ###
> ** [beeender](/beeender) ** commented [Oct 31, 2023](#issuecomment-1787289669)

No, this is caused by the changes in 3.0.

**Pull request merged**
