### PR TITLE
Add clang-format and editorconfig

### PR DESCRIPTION
**Pull request by beeender**
- clang-format is from https://groups.google.com/a/greenplum.org/g/gpdb-dev/c/rHb4DjSd1iI/m/FKPbqwYcBAAJ
- See editorconfig at https://editorconfig.org/

### CODE REVIEW

**Comment by beeender** [comment]
Let me know if you have a better clang-format.

**Comment by xuebinsu** [comment]
It is good to have a formatter. Can we automate this, e.g., force formatting on pushing to Github? It is hard to remember so many things when committing code.

**Review by Sasasu — APPROVED** [review]
should we format all existing before publishing a new version?

**Comment by beeender** [comment]
> It is good to have a formatter. Can we automate this, e.g., force formatting on pushing to Github? It is hard to remember so many things when committing code.

We can either make a pre-git commit hook? any automation formatting after commit will change the SHA1 which is not accepted. We can have a formatted checker for CI.

**Comment by beeender** [comment]
> should we format all existing before publishing a new version?

I am struggling with this, shall we?

**Comment by xuebinsu** [comment]
Hi @beeender and @Sasasu ,

> We can either make a pre-git commit hook?
This sounds good. Then how can we ensure that the pre-commit hook is installed on everyone's machine? How about installing it before `make installcheck`?

> We can have a formatted checker for CI.
This sounds good too. Let's add the check in the scripts.

 > should we format all existing before publishing a new version?
I think so. I think we should avoid big changes after releasing a major version.

**Comment by higuoxing** [comment]
> > We can either make a pre-git commit hook?
> 
> This sounds good. Then how can we ensure that the pre-commit hook is installed on everyone's machine? How about installing it before `make installcheck`?

A script called `git-clang-format` is shipped with `clang-format`. If you have installed `clang-format`, you can invoke it via

```bash
$ git clang-format <commit>
```

> > We can have a formatted checker for CI.
> 
> This sounds good too. Let's add the check in the scripts.

+1 to this idea.

**Review by xuebinsu — APPROVED** [review]

**Pull request merged**
